### PR TITLE
Required SimplePie version

### PR DESCRIPTION
**Pull request by tonioriol**
The purpose of this pull req is fix the requirement of "dev-master" version of SimplePie package. Currently that branch doesn't exist any more. I replaced the version to a more convenient "1.x".

This is my first pull req, please let me know if I'm doing something wrong.

### CODE REVIEW

**Comment by awjudd** [comment]
In order to use `master`, you would need to change your minimum stability to `dev`.  This is where the difference lies.  The issue with using tag `1.3.1` is it hasn't been pushed to in years.  `dev-master` has some changes from 11 months ago to the core library.

What we should be doing is requesting that a new tag be cut of SimplePie and then once that is done, then we can put your change in.

**Comment by tonioriol** [comment]
Ok, i understand. So the only thing I have to do to make it work is change the `"minimum-stability"` to `"stable"`. Regarding the version change in the package's `composer.json` is not ok because the latest tag (`1.3.1`) is to old, am i right?

**Comment by awjudd** [comment]
You would need to change the minimum stability to `dev`, because `master` is a `dev` branch.  Technically having the version number there is the right thing to do however, because it was so old I had opted to not use that one in order to use the version that has some of the new bug fixes in place.

**Comment by tonioriol** [comment]
Ok thanks :)

**Pull request closed without merging**
